/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/golf-courses": {
    /** fetches all golf courses */
    get: operations["get_all_courses_golf_courses_get"];
  };
  "/golf-courses/{id}": {
    /** fetches a single golf course */
    get: operations["get_single_course_golf_courses__id__get"];
  };
  "/weather/{loc}": {
    get: operations["get_weather_weather__loc__get"];
  };
  "/golf-conditions/{loc}": {
    get: operations["golf_conditions_golf_conditions__loc__get"];
  };
}

export interface components {
  schemas: {
    /** GeoJSONFeatureCollection */
    GeoJSONFeatureCollection: {
      /** Type */
      type: string;
      /** Features */
      features: components["schemas"]["PointFeature"][];
    };
    /** GolfCourse */
    GolfCourse: {
      /** Id */
      id?: number;
      /** Region */
      Region?: number;
      /** Coursename */
      CourseName?: string;
      /** Address */
      Address?: string;
      /** City */
      City?: string;
      /** Zip */
      Zip?: string;
      /** State */
      State?: string;
      /** Holes */
      Holes?: number;
      /** Phone */
      Phone?: string;
      /** Latitude */
      Latitude?: number;
      /** Longitude */
      Longitude?: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LatLng */
    LatLng: {
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
    };
    /** Period */
    Period: {
      /** Timestamp */
      timestamp: number;
      range: components["schemas"]["TimeRange"];
      precip: components["schemas"]["Precip"];
      temp: components["schemas"]["TempLike"];
      dewpoint: components["schemas"]["TempLike"];
      windSpeed: components["schemas"]["WindSpeed"];
      weather: components["schemas"]["Weather"];
    };
    /** Place */
    Place: {
      /** Name */
      name: string;
      /** State */
      state: string;
      /** Country */
      country: string;
    };
    /** PointFeature */
    PointFeature: {
      /** Type */
      type: string;
      geometry: components["schemas"]["PointGeometry"];
      /** Properties */
      properties?: unknown;
    };
    /** PointGeometry */
    PointGeometry: {
      /** Type */
      type: string;
      /** Coordinates */
      coordinates: number[];
    };
    /** Precip */
    Precip: {
      /** Maxtimestamp */
      maxTimestamp: number;
      /** Maxdatetimeiso */
      maxDateTimeISO: string;
      /** Mintimestamp */
      minTimestamp: number;
      /** Mindatetimeiso */
      minDateTimeISO: string;
      /** Maxmm */
      maxMM: number;
      /** Minmm */
      minMM: number;
      /** Avgmm */
      avgMM: number;
      /** Totalmm */
      totalMM: number;
      /** Maxin */
      maxIN: number;
      /** Minin */
      minIN: number;
      /** Avgin */
      avgIN: number;
      /** Totalin */
      totalIN: number;
    };
    /** RatingResponse */
    RatingResponse: {
      scores: components["schemas"]["RatingScores"];
      /** Rating */
      rating: number;
      loc: components["schemas"]["LatLng"];
      place: components["schemas"]["Place"];
      /** Periods */
      periods: components["schemas"]["Period"][];
    };
    /** RatingScores */
    RatingScores: {
      /** Temp */
      temp: number;
      /** Wind */
      wind: number;
      /** Precip */
      precip: number;
      /** Dew */
      dew: number;
    };
    /** TempLike */
    TempLike: {
      /** Maxtimestamp */
      maxTimestamp: number;
      /** Maxdatetimeiso */
      maxDateTimeISO: string;
      /** Mintimestamp */
      minTimestamp: number;
      /** Mindatetimeiso */
      minDateTimeISO: string;
      /** Maxc */
      maxC: number;
      /** Minc */
      minC: number;
      /** Avgc */
      avgC: number;
      /** Maxf */
      maxF: number;
      /** Minf */
      minF: number;
      /** Avgf */
      avgF: number;
    };
    /** TimeRange */
    TimeRange: {
      /** Maxtimestamp */
      maxTimestamp: number;
      /** Maxdatetimeiso */
      maxDateTimeISO: string;
      /** Mintimestamp */
      minTimestamp: number;
      /** Mindatetimeiso */
      minDateTimeISO: string;
      /** Count */
      count: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: string[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** Weather */
    Weather: {
      /** Phrase */
      phrase: string;
      /** Primary */
      primary: string;
    };
    /** WindSpeed */
    WindSpeed: {
      /** Maxtimestamp */
      maxTimestamp: number;
      /** Maxdatetimeiso */
      maxDateTimeISO: string;
      /** Mintimestamp */
      minTimestamp: number;
      /** Mindatetimeiso */
      minDateTimeISO: string;
      /** Maxkts */
      maxKTS: number;
      /** Mixkts */
      mixKTS: number;
      /** Avxkts */
      avxKTS: number;
      /** Maxkph */
      maxKPH: number;
      /** Mixkph */
      mixKPH: number;
      /** Avxkph */
      avxKPH: number;
    };
  };
}

export interface operations {
  /** fetches all golf courses */
  get_all_courses_golf_courses_get: {
    parameters: {
      query: {
        f?: string;
        id?: number;
        Region?: number;
        CourseName?: string;
        Address?: string;
        City?: string;
        Zip?: string;
        State?: string;
        Holes?: number;
        Phone?: string;
        Latitude?: number;
        Longitude?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": Partial<
            components["schemas"]["GeoJSONFeatureCollection"]
          > &
            Partial<components["schemas"]["GolfCourse"][]>;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** fetches a single golf course */
  get_single_course_golf_courses__id__get: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GolfCourse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_weather_weather__loc__get: {
    parameters: {
      path: {
        loc: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  golf_conditions_golf_conditions__loc__get: {
    parameters: {
      path: {
        loc: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RatingResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}

export interface external {}
